swagger: '2.0'
info:
  title: DevOps RESTful Project
  description: API for portfolio management, implemented for the NYU DevOps course. 
  version: "1.0"
host: portfoliomgmt.mybluemix.net
schemes:
  - https
  - http
basePath: /api/v1
produces:
  - application/json
paths:
  /portfolios:
    get:
      summary: All portfolios
      description:
        IMPORTANT - Admin username is "admin" with password "admin_password".
        The portfolios endpoint returns all portfolios stored on the system.
        The response includes the user who owns the portfolio, the number of
        assets in the portfolio and the net asset value of the portfolio. In
        addition, a link is provided for each portfolio to its full object.
      tags:
        - Portfolios
      responses:
        200:
          description: An array of portfolios
          schema:
            type: array
            items:
              $ref: '#/definitions/portfolio'
    post:
      summary: Create a new user portfolio
      description: Create a new user portfolio
      parameters:
        - name: body
          in: body
          description: New user for which a portfolio should be created
          required: true
          schema:
            properties:
              user:
                type: string
                default: "john"
              password:
                type: string
                default: "12345"
      tags:
        - Portfolios
      responses:
        201:
          description: Portfolio successfully created
        400:
          description: Body is not well formed (more details in error message)
          schema: {$ref: '#/definitions/error_data'}
        409:
          description: A portfolio for the user already exists
          schema: {$ref: '#/definitions/error_userexists'}
  /portfolios/{user}:
    delete:
      summary: Delete a user
      description: Removes a user from the database.
      tags:
        - Portfolios
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
      responses:
        204:
          description: The user has been deleted or does not exist
  /portfolios/{user}/assets:
    get:
      summary: Get the assets of the portfolio of a user
      description: Returns the asset ID and the asset name of each assets present in the portfolio owned by the specified user.
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
      tags:
        - Portfolios
      responses:
        200:
          description: An array of assets
          schema:
            type: array
            items:
              $ref: '#/definitions/asset_description'
        404:
          description: User not found
          schema: {$ref: '#/definitions/error_userdoesnotexist'}
    post:
      summary: Add new asset
      description: Adds an amount of a new asset to the user's portfolio. If this asset exists already, this will raise an error.
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
        - name: body
          in: body
          description: The unique asset id of the asset being added to the portfolio
          required: true
          schema:
            properties:
              asset_id:
                type: integer
                default: 0
              quantity:
                type: integer
                default: 10
      tags:
        - Portfolios
      responses:
        201:
          description: The asset was added to the portfolio
        400:
          description: Body is not well formed or the asset id does not exist
          schema: {$ref: '#/definitions/error_data'}
        404:
          description: User not found or there is no data associated with user
          schema: {$ref: '#/definitions/error_userdoesnotexist'}
        409:
          description: Asset with this asset ID already exist in the portfolio
          schema: {$ref: '#/definitions/error_assetexists'}
  /portfolios/{user}/assets/{asset_id}:
    get:
      summary: Get the quantity and total value (NAV) of an asset in a portfolio
      description: Given a user and an asset, returns the quantity and net asset value of the asset in the user's porfolio.
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
        - name: asset_id
          in: path
          description: The asset id of the asset
          required: true
          type: string
          default: "0"
      tags:
        - Portfolios
      responses:
        200:
          description: An object containing the quantity and net asset value of the asset
          schema: 
            $ref: '#/definitions/asset_numbers'
        404:
          description: User not found or asset not found in portfolio
          schema: {$ref: '#/definitions/error_userdoesnotexist'}
    put:
      summary: Update an existing asset
      description: Updates the quantity of an asset held in the portfolio of a user
      tags:
        - Portfolios
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
        - name: asset_id
          in: path
          description: The asset id of the asset to update
          required: true
          type: string
          default: "0"
        - name: body
          in: body
          description: The quantity to add or subtract from the current quantity of this asset in the portfolio
          required: true
          schema:
            properties:
              quantity:
                type: integer
                default: -3
      responses:
        200:
          description: The quantity has been updated successfully
        400:
          description: Body is not well formed (more information in the error message) or the quantity to subtract will yield a negative quantity result (not allowed here).
          schema: {$ref : '#/definitions/error_data'}
        404:
          description: User not found, or user data is empty or the asset ID not found in the user portfolio.
          schema: {$ref: '#/definitions/error_userdoesnotexist'}
    delete:
      summary: Delete an asset from a user's portfolio
      description: Will delete an asset from the user's portfolio. If the asset does not exist in the user's portfolio, operation will treat that like a successful delete.
      tags:
        - Portfolios
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
        - name: asset_id
          in: path
          description: The asset id to delete
          required: true
          type: string
          default: "0"
      responses:
        204:
          description: Deleted successfully
  /portfolios/{user}/nav:
    get:
      summary: Get the net asset value (NAV) of the portfolio
      description: Given a username, find the net asset value of the portfolio belonging to the user
      tags:
        - Portfolios
      parameters:
        - name: user
          in: path
          description: Username of portfolio owner
          required: true
          type: string
          default: "john"
      responses:
        200:
          description: An object containing the net asset value of the portfolio
          schema: 
            $ref: '#/definitions/nav'
        404:
          description: User not found
          schema: {$ref: '#/definitions/error_userdoesnotexist'}
    
          
definitions:
  portfolio:
    type: object
    properties:
      user:
        type: string
        description: The username of the user who owns this portfolio
        default: "john"
      numberOfAssets:
        type: integer
        description: The number of assets held within the portfolio
        default: 1
      netAssetValue:
        type: number
        description: The net asset value of all the assets within the portfolio
        default: 125.56
      links:
        type: array
        items: {"$ref": "#/definitions/link"}
        description: An array of links related to the portfolio
  link:
    type: object
    properties:
      rel:
        type: string
        description: The relationship of the link to the object
        default: "self"
      href:
        type: string
        description: the url to the link
        default: "hostname/api/v1/users/john/assets/0"
  asset_description:
    type: object
    properties:
      id:
        type: integer
        description: The unique id of the asset
        default: 0
      name:
        type: string
        description: The name of the asset
        default: "gold"
  asset_numbers:
    type: object
    properties:
      quantity:
        type: integer
        description: The quantity of the asset in the user portfolio
        default: 10
      nav:
        type: number
        description: The net asset value of this asset (quantity * price)
        default: 125.56
  nav:
    type: object
    properties:
      nav:
        type: number
        description: A net asset value of a portfolio
        default: 125.56
        
  error_data:
    type: object
    properties:
      error:
        type: string
        description: Highlights that the data is not JSON or does not have the necessary required information.
        default: "The data is not valid."
        
  error_userexists:
    type: object
    properties:
      error:
        type: string
        description: The user already exists in the database
        default: "The user already exists in the database."
        
  error_userdoesnotexist:
    type: object
    properties:
      error:
        type: string
        description: The user does not exist in the database
        default: "The user does not exist in the database."
        
  error_assetexists:
    type: object
    properties:
      error:
        type: string
        description: Asset with id x already exists in portfolio
        default: "Asset is already present in the portfolio of the user."
        
        